# Generated by Django 2.2 on 2021-04-19 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm2', '0002_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
