# Generated by Django 2.2 on 2021-04-19 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm2', '0004_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pet',
            new_name='email',
        ),
    ]
