# Generated by Django 2.2 on 2021-04-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm2', '0007_author_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='orm2.Book'),
        ),
    ]
